name: "${name}"
main: "${group}.Pl3xMapSigns"
version: "${version}"
api-version: "${apiVersion}"
load: "POSTWORLD"
authors: ${authors}
description: "${description}"
website: "${website}"

softdepend:
  - Pl3xMap

permissions:
  pl3xmap.signs.admin:
    description: Gives access to add/remove signs by clicking
    default: op